#!/bin/sh

VERSION=4.9.35
BOOT=/boot
IMG=$BOOT/initrd-$VERSION.img
DEV=/dev/sda7

mkinitrd -c -o $IMG -k $VERSION -m ext4 -f ext4 -r $DEV
cp $IMG $BOOT/initrd.gz

grub-mkconfig -o $BOOT/grub/grub.cfg

